local content = require "nohands.content"

describe("content sources", function()
  it("buffer source returns text and meta", function()
    vim.api.nvim_buf_set_lines(0, 0, -1, false, { "line1", "line2" })
    local c = content.buffer(0)
    assert.is_not_nil(c.text:match "line1")
    assert.equals("buffer", c.meta.type)
  end)

  it("range source returns correct lines", function()
    vim.api.nvim_buf_set_lines(0, 0, -1, false, { "a", "b", "c", "d" })
    local c = content.range(1, 2)
    assert.equals("b\nc", c.text)
    assert.equals("range", c.meta.type)
  end)

  it("surrounding source returns contextual lines", function()
    vim.api.nvim_buf_set_lines(0, 0, -1, false, { "x", "y", "z", "q", "w" })
    vim.api.nvim_win_set_cursor(0, { 3, 0 })
    local c = content.surrounding(1, 1)
    assert.is_not_nil(c.text:match "y")
    assert.is_not_nil(c.text:match "z")
    assert.is_not_nil(c.text:match "q")
    assert.equals("surrounding", c.meta.type)
  end)

  it("selection source respects visual marks including reversed ranges", function()
    vim.api.nvim_buf_set_lines(0, 0, -1, false, { "one", "two", "three", "four" })
    -- Simulate a visual selection from line 2 to line 3 (both directions)
    vim.fn.setpos("'<", { 0, 2, 1, 0 })
    vim.fn.setpos("'>", { 0, 3, 5, 0 })
    local forward = content.selection()
    assert.equals("two\nthree", forward.text)

    vim.fn.setpos("'<", { 0, 3, 5, 0 })
    vim.fn.setpos("'>", { 0, 2, 1, 0 })
    local reversed = content.selection()
    assert.equals("two\nthree", reversed.text)
  end)
end)
